//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desarrolladora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desarrolladora()
        {
            this.Videojuego = new HashSet<Videojuego>();
        }
    
        public int IdDesarrollador { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Popularidad { get; set; }
        public string Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videojuego> Videojuego { get; set; }
    }
}
